### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by kiran-surya** [attardi/deepnl#6] opened 2015-08-21 10:12 UTC
Facing following issue now:

... with the following parameters:

```
    Input layer size: 400
    Hidden layer size: 300
    Output size: 17
```

Starting training with 22138 sentences
Training for up to 40 epochs
Traceback (most recent call last):
  File "bin/dl-ner.py", line 331, in <module>
    main()
  File "bin/dl-ner.py", line 314, in main
    args.threads)
  File "deepnl/trainer.pyx", line 123, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3526)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 341, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8359)
    scores = self.tagger._tag_sequence(sent, True)
  File "deepnl/tagger.pyx", line 72, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3605)
    cpdef np.ndarray[FLOAT_t,ndim=2] _tag_sequence(self,
  File "deepnl/tagger.pyx", line 101, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3213)
    np.concatenate((self.pre_padding,
ValueError: all the input arrays must have same number of dimensions

**Comment by attardi** [comment] 2015-08-21 13:25
That is weird. Which version of Numpy are you using?
I made a few changes and committed new version 1.3.6.
I tested it successfully on the Conll 2003 data.

**Comment by kiran-surya** [comment] 2015-08-21 13:28
numpy1.9

**Comment by kiran-surya** [comment] 2015-08-21 13:38
With latest code, this issue is resolved, but i'm facing new issue:
Starting training with 22138 sentences
Training for up to 40 epochs
Traceback (most recent call last):
  File "bin/dl-ner.py", line 336, in <module>
    main()
  File "bin/dl-ner.py", line 319, in main
    args.threads)
  File "deepnl/trainer.pyx", line 123, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3736)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 341, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8610)
    scores = self.tagger._tag_sequence(sent, True)
  File "deepnl/tagger.pyx", line 72, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3717)
    cpdef np.ndarray[FLOAT_t,ndim=2] _tag_sequence(self,
  File "deepnl/tagger.pyx", line 123, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3514)
    self.converter.lookup(window, vars.input)
  File "deepnl/extractors.pyx", line 147, in deepnl.extractors.Converter.lookup (deepnl/extractors.cpp:4285)
    np.copyto(out[start:end], extractor[feature])
  File "deepnl/extractors.pyx", line 209, in deepnl.extractors.Extractor.__getitem__ (deepnl/extractors.cpp:5698)
    return self.table[feature]
IndexError: index 130396 is out of bounds for axis 0 with size 130000

**Comment by attardi** [comment] 2015-08-21 13:49
It looks like you are using inconsistent versions of vocab and vectors, probably created by previous runs.
Reset the files to the originals and retry.

**Comment by kiran-surya** [comment] 2015-08-21 14:12
It looks like i'm getting value error again. In the last run i forgot to reset vocabulary, so i got index out of bound issue. Now i'm getting value error after resetting.
Creating capitalization features...
Generated 5 feature vectors with 5 features each.
Loading suffix list...
Generated 457 feature vectors with 5 features each.
Loading gazetteers
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Creating new network...
... with the following parameters:

```
    Input layer size: 400
    Hidden layer size: 300
    Output size: 17
```

Starting training with 22138 sentences
Training for up to 40 epochs
Traceback (most recent call last):
  File "bin/dl-ner.py", line 336, in <module>
    main()
  File "bin/dl-ner.py", line 319, in main
    args.threads)
  File "deepnl/trainer.pyx", line 123, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3736)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 341, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8610)
    scores = self.tagger._tag_sequence(sent, True)
  File "deepnl/tagger.pyx", line 72, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3717)
    cpdef np.ndarray[FLOAT_t,ndim=2] _tag_sequence(self,
  File "deepnl/tagger.pyx", line 101, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3314)
    np.concatenate((self.pre_padding,
ValueError: all the input arrays must have same number of dimensions

**Comment by kiran-surya** [comment] 2015-08-21 14:21
I'm using python2.7, numpy1.9, linux machine

**Comment by attardi** [comment] 2015-08-21 14:55
Please show me the parameters you are using to invoke the script, so that I can try to reproduce the error.

**Comment by kiran-surya** [comment] 2015-08-21 14:59
python2.7 bin/dl-ner.py ner.dnn -t ~/data/train_new.iob --vocab ~/data/vocab.txt --vectors ~/data/vectors.txt --caps --suffix  --suffixes ~/data/suffix.lst --gazetteer ~/data/eng.list -e 40 --variant senna -l 0.01 -w 5 -n 300 -v

i'm training on my specific data.

**Comment by attardi** [comment] 2015-08-21 15:10
For me with these parameters it works fine.

**Comment by kiran-surya** [comment] 2015-08-21 15:30
can you send me the sample format of train, vocal and vectors file you are using.

**Comment by attardi** [comment] 2015-08-21 15:36
I am using the embeddings from the SENNA distribution: the vocabulary is just a list of one word per line, the vector a list of float numbers, one per line, space separated.
You format must be correct, since the reader has no problems loading them.
The training data is in IOB format: one token per line, fields tab separated.
Sentences are separated by an empty line.
The first filed is the form, the last one the tag, e.g.

EU      NNP     B-ORG
rejects VBZ     O
German  JJ      B-MISC
call    NN      O
to      TO      O
boycott VB      O
British JJ      B-MISC
lamb    NN      O
.       .       O

Peter   NNP     B-PER
Blackburn       NNP     I-PER

**Comment by kiran-surya** [comment] 2015-08-21 15:55
Even my sample training data is like this:

EU      NNP     B-ORG
rejects VBZ     O
German  JJ      B-MISC
call    NN      O
to      TO      O
boycott VB      O
British JJ      B-MISC
lamb    NN      O
.       .       O

Peter   NNP     B-PER

Every other input file is in the format described by you. I'm getting the same error even with nlpnet.

**Comment by kiran-surya** [comment] 2015-08-21 16:03
Even i'm using senna distribution.

**Comment by kiran-surya** [comment] 2015-08-22 03:36
Hi @attardi 

Do you suspect any issue with gazetteer file ? what could be the issue ? Even on sample training file (conll 2003 data), i'm getting this issue.

**Comment by kiran-surya** [comment] 2015-08-22 16:01
How much time it takes to train on data ~ 0.3 million sentences for 40 epochs approx. (8G, 8 core machine)

**Comment by isabelleaugenstein** [comment] 2015-10-23 15:33
I got the same error, but only for some training files. For me what fixed was to substitute consecutive blank lines in the file with single blank lines and to make sure the file doesn't start or end with a blank line.

**Closed as completed** 2016-04-23 16:49 UTC
